name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Windows CMake
    runs-on: windows-latest
    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      # Enable vcpkg's built-in GitHub Actions binary caching
      VCPKG_BINARY_SOURCES: clear;x-gha,readwrite

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Bootstrap vcpkg
        shell: pwsh
        run: |
          Copy-Item vcpkg.exe ./vcpkg/vcpkg.exe
          Copy-Item github-actions-cache-adapter.mjs ./vcpkg/github-actions-cache-adapter.mjs

      - name: Configure CMake
        shell: pwsh
        run: |
          cmake -S . -B build -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake"

      - name: Build
        shell: pwsh
        run: |
          cmake --build build --config Release --parallel

      - name: Test
        shell: pwsh
        run: |
          ctest --test-dir build -C Release --output-on-failure

      - name: Determine artifact path
        id: artifact
        shell: pwsh
        run: |
          "artifact=build\\Release\\hello_cpp.exe" >> $env:GITHUB_OUTPUT

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-hello_cpp
          path: ${{ steps.artifact.outputs.artifact }}
